# Workflow name
name: Auto-testing-builds & Deployments

# This workflow is triggered on every push to the repository.
on:
  push:

env:
  builds-directory: ~/builds/athemes

# Defines the jobs that will be executed as part of this workflow.
jobs:
  create-testing-build:
    uses: awesomemotive/Sydney/.github/workflows/build.yml@main

  upload-testing-build:
    name: Prepare and upload builds in hub.wpforms.com/builds
    runs-on: self-hosted
    needs: create-testing-build
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    # Defines the sequence of steps that make up the \'build\' job.
    steps:
      # This action exposes GitHub environment variables, making them available in subsequent steps.
      - name: GitHub Environment Variables Action
        uses: FranzDiebold/github-env-vars-action@v2.8.0

      - name: Set Project Name
        run: |
          repo_full_name="${{ github.repository }}"
          repo_short_name="${repo_full_name##*/}"
          echo "PROJECT_NAME=${repo_short_name,,}" >> $GITHUB_ENV

      # Uploads the build to the server using rsync over SSH.
      # --rsh: Specifies the remote shell to use (ssh with specific options).
      # -o StrictHostKeyChecking=no: Disables host key checking.
      # --ignore-times: Doesn\'t skip files that have the same size and modification time.
      # --archive: Archive mode, equivalent to -rlptgoD.
      # --verbose: Increases verbosity.
      # --compress: Compresses file data during the transfer.
      # --human-readable: Outputs numbers in a human-readable format.
      # --progress: Shows progress during transfer.
      # --whole-file: Copies files whole (without delta-xfer algorithm).
      - name: Upload to hub.wpforms.com
        run: |
          rsync --rsh="ssh -o StrictHostKeyChecking=no -p18765" \
                --ignore-times \
                --archive \
                --verbose \
                --compress \
                --human-readable \
                --progress \
                --whole-file \
                ${{ env.builds-directory }}/${{ env.PROJECT_NAME }}/${{ env.CI_REF_NAME_SLUG }}/${{ env.PROJECT_NAME }}.zip \
                staging@34.68.130.55:/home/staging/shared/hub.wpforms.com/builds/athemes/${{ env.PROJECT_NAME }}/${{ env.CI_REF_NAME_SLUG }}/