# GitHub Actions Workflow to deploy on production demos site

name: Deploy to demos network

on:
  push:
    branches:
      - master

jobs:
  create-project-build:
    uses: awesomemotive/Sydney/.github/workflows/build.yml@master

  deploy:
    runs-on: self-hosted
    needs: create-project-build

    steps:
      - name: Set Project Name
        run: |
          repo_full_name="${{ github.repository }}"
          repo_short_name="${repo_full_name##*/}"
          echo "PROJECT_NAME=${repo_short_name,,}" >> $GITHUB_ENV

      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: ${{ env.PROJECT_NAME }}
          path: ${{ env.PROJECT_NAME }}

      - name: Sync files with SSH
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "${{ env.PROJECT_NAME }}/"
          REMOTE_HOST: ${{secrets.SERVER_REMOTE_HOST}}
          REMOTE_USER: ${{secrets.SERVER_REMOTE_USER}}
          REMOTE_PORT: "22"
          TARGET: "www/wp-content/themes/${{ env.PROJECT_NAME }}/"
        