# GitHub Actions Workflow for bundling production theme zip file.

name: Create WP production theme zip file

on:
  push:
    tags:
      - "*"

jobs:
  create-project-build:
    uses: awesomemotive/Sydney/.github/workflows/build.yml@main

  build-theme-zip-asset:
    runs-on: self-hosted
    needs: create-project-build
    steps:
      - name: Set Project Name
        run: |
          repo_full_name="${{ github.repository }}"
          repo_short_name="${repo_full_name##*/}"
          echo "PROJECT_NAME=${repo_short_name,,}" >> $GITHUB_ENV

      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: ${{ env.PROJECT_NAME }}
          path: ${{ env.PROJECT_NAME }}
      - run: zip -qq -r ${{ env.PROJECT_NAME }}.zip ${{ env.PROJECT_NAME }}

      - name: Upload release attachment
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.PROJECT_NAME }}.zip
          tag: ${{ github.ref_name }}
          release_name: "Sydney ${{ github.ref_name }}"
          overwrite: true
          body: "Changelog: https://athemes.com/changelog/sydney/"